# Copyright 2018 M. Riechert and D. Meyer. Licensed under the MIT License.

image: Visual Studio 2017 # See https://www.appveyor.com/docs/build-environment/

clone_depth: 50

skip_commits:
  files:
    - 'README*'

environment:
  global:
    WRF_REPO: WRF-CMake/wrf
    WRF_COMMIT: wrf-cmake
    BUILD_SYSTEM: CMake

  matrix:
    - BUILD_TYPE: Debug
      CC: gcc
      FC: gfortran
      MODE: serial
      NESTING: basic
      GRIB1: 0
      GRIB2: 1

    - BUILD_TYPE: Debug
      CC: gcc
      FC: gfortran
      MODE: dmpar
      NESTING: basic
      GRIB1: 0
      GRIB2: 1

install:
  - ps: .ci\windows\dump-vm-specs.ps1
  - cd ..
  - git clone --depth=100 --no-single-branch https://github.com/%WRF_REPO%.git WRF
  - cd WRF
  - git checkout %WRF_COMMIT%
  - call .ci\windows\setup-dependencies.bat
  - call .ci\windows\install-wrf.bat
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - call .ci\windows\install-wps.bat
